"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-05

Covers all four application tables: users, repos, code_chunks,
query_history. Hand-written rather than autogenerated because
`alembic revision --autogenerate` requires a live DB connection to
diff against, which isn't available in every environment this repo
is built in -- this migration is the source of truth for a fresh DB.

Deliberately does NOT create the pgvector HNSW index on code_chunks --
that's built by app/services/embedder.py only after embeddings exist
(building it against an empty column is wasted, and it must be rebuilt
as vectors are added anyway).
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = 1536

index_status_enum = postgresql.ENUM(
    "pending", "cloning", "parsing", "embedding", "ready", "failed",
    name="indexstatus",
)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    index_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("github_id", sa.String(), nullable=False),
        sa.Column("github_username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("plan", sa.String(), server_default="free"),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("queries_this_month", sa.Integer(), server_default="0"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
    )
    op.create_index("ix_users_github_id", "users", ["github_id"], unique=True)
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "repos",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("github_full_name", sa.String(), nullable=False),
        sa.Column("github_url", sa.String(), nullable=False),
        sa.Column("default_branch", sa.String(), server_default="main"),
        sa.Column("index_status", index_status_enum, server_default="pending"),
        sa.Column("last_indexed_commit_sha", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now()),
    )
    op.create_index("ix_repos_owner_id", "repos", ["owner_id"])

    op.create_table(
        "code_chunks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("repo_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("repos.id"), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("chunk_type", sa.String(), nullable=False),
        sa.Column("symbol_name", sa.String(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
    )
    op.create_index("ix_code_chunks_repo_id", "code_chunks", ["repo_id"])

    op.create_table(
        "query_history",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("repo_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("repos.id"), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
    )
    op.create_index("ix_query_history_user_id", "query_history", ["user_id"])
    op.create_index("ix_query_history_repo_id", "query_history", ["repo_id"])


def downgrade() -> None:
    op.drop_table("query_history")
    op.drop_table("code_chunks")
    op.drop_table("repos")
    op.drop_table("users")
    index_status_enum.drop(op.get_bind(), checkfirst=True)
    # Not dropping the `vector` extension -- other objects may depend on it.
